{"uuid": "95edeb74-d66d-43e2-93b2-299a8fa65381", "children": ["56ded7ff-8545-45b2-8b3e-a1031f7c1228"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'msedgedriver.exe' executable may have wrong permissions.\n\n", "trace": "  File \"G:\\OrangeHRM\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"G:\\OrangeHRM\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"G:\\OrangeHRM\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"G:\\OrangeHRM\\testCases\\conftest.py\", line 20, in setup\n    driver = webdriver.Edge()\n             ^^^^^^^^^^^^^^^^\n  File \"G:\\OrangeHRM\\venv\\Lib\\site-packages\\selenium\\webdriver\\edge\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"G:\\OrangeHRM\\venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 53, in __init__\n    self.service.start()\n  File \"G:\\OrangeHRM\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 105, in start\n    self._start_process(self._path)\n  File \"G:\\OrangeHRM\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 221, in _start_process\n    raise WebDriverException(\n"}, "start": 1692385603597, "stop": 1692385609915}], "start": 1692385603597, "stop": 1692385610118}